### ISSUE TITLE
Oval pads on rotated footprint appear horizontal

### ISSUE THREAD

**Issue by UnguidedFreedom** [gregdavill/kicadScripts#3]
Hello,

First of all thank you so much for those scripts, they are amazing and the renders are gorgeous! 

I have a board with a USB connector at a 35° angle. It has two oval pads, but on the renders, the pads show up horizontally instead of being at an angle.

I just thought I'd let you know :)

![Screen Shot 2019-04-21 at 7 49 12 PM](https://user-images.githubusercontent.com/3374479/56468374-c40edf80-646e-11e9-99d5-6b6c290e5d0b.png)

**Comment by gregdavill** [comment]
I noticed this a few weeks ago with one of my board designs. Except mine were only 0°/90°/180°/270° 

I've just pushed some code that may help. 
Can you test it and let me know, a quick test here on KiCad 5.1 with a 35° slot seems to work.

**Comment by UnguidedFreedom** [comment]
Thank you for your fast reply! 

I have tested the updated code, and the hole is displayed at a different angle but it still isn't the correct one. 

If it helps, the pad is rotated 90° within the footprint, and the footprint is rotated 215° on the board.

![Screen Shot 2019-04-21 at 9 51 25 PM](https://user-images.githubusercontent.com/3374479/56469663-f2e18180-647f-11e9-8910-075e2812d52c.png)

**Comment by gregdavill** [comment]
Thanks for testing that! I think my code is actually mirroring the rotation. (ie rotating in the opposite direction).

I have reproduced your results and just pushed an update.

**Comment by UnguidedFreedom** [comment]
It works perfectly now, thank you very much!
